In [ ]:
                                                    #NUMPY

In [ ]:
numpy will store data in continous memory blocks,making them super fast for calculation

In [3]:
import numpy as np

In [2]:
import time

In [5]:
# numpy array
array_data = np.arange(1_00_000)
start = time.time()
sum_array = array_data*2
end = time.time()
print("numpy array time:",end - start)

numpy array time: 0.002263784408569336


## creating of arrays in numpy:

numpy as several arrays:
1.np.arrays() = create a list from a python list
2.np.zeros() =  all zeros
3.np.ones() = all ones
4.np.arange() = range of numbers(like python range)
5.np.linspace() = evenly spaced numbers between two points



In [6]:
array1 = np.array([1,2,3])
print(array1)

[1 2 3]


In [8]:
zero=np.zeros((5,7))
print(zero)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [14]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
range = np.arange(0,10,2)
print(range)

[0 2 4 6 8]


In [19]:
linspace = np.linspace(0,   1,   5)
print(linspace)

[0.   0.25 0.5  0.75 1.  ]


In [23]:
#array operations
arr = np.array([2,3,4,5])

#scalar operation:
print(arr + 10) #adds 10 to each element
print(arr * 10)# multiply 10 to each element

#element wise operation
arr1 = np.array([2,4,6,8])
print(arr + arr1)
print(arr * arr1)

[12 13 14 15]
[20 30 40 50]
[ 4  7 10 13]
[ 4 12 24 40]


In [35]:
## indexing and slicing

# creating a multi dimensional(2D) sliccing (with row and co;umns)matrix
#1.indexing
arr = np.array([[2,3,4,5],
                [10,15,20,30],
                [50,60,70,80]])
print("first row:",arr[2])
print("element at:",arr[1,2]) #this is 2nd row ,3rd column

first row: [50 60 70 80]
element at: 20


In [34]:
# 2.slicing
arr = np.array([[2,3,4,5],
                [10,15,20,30],
                [50,60,70,80]])

print("first two rows:",arr[0:2])
print("first column:",arr[:2])

first two rows: [[ 2  3  4  5]
 [10 15 20 30]]
first column: [[ 2  3  4  5]
 [10 15 20 30]]


In [ ]:
##BROADCASTING
it allows operations between arrays of defferent shapes - as long as they are compatible.
for example : adding a 1d array to each row of 2d array

In [36]:
a=np.array([[1,2,3],
            [4,5,6],    #this is 2d
            [7,8,9]])
b = np.array([10,20,30])  #this is 1d
print("broadcasted result:\n",a+b)

broadcasted result:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [60]:
                                                          ## assingment 
a= np.array([[1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15],
            [16,17,18,19,20],
            [21,22,23,24,25]])
print(a[1:4])
            

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [51]:
a= np.array([1,2,3,4,5,6,7,8,9,10])
a[a % 2 ==0] -=1      #the even number should divide by 2 if the reminder is 0 then the element should -1
print(a)

[1 1 3 3 5 5 7 7 9 9]


In [53]:
a= np.array([[1,2,3,4],
            [6,7,8,9],
            [11,12,13,14],
            [16,17,18,19]])
b = np.array([1,2,3,4])

print("broadcasted result:\n",a+b)
             

broadcasted result:
 [[ 2  4  6  8]
 [ 7  9 11 13]
 [12 14 16 18]
 [17 19 21 23]]
